# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Team-90s' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Team-90s
 pod 'Alamofire'
 pod 'AlamofireImage'
 pod 'lottie-ios'
 pod 'KakaoOpenSDK'
end
